#+title:  Class Templates
#+SETUPFILE: ../../../org-templates/level-3.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction

This module introduces metaprogramming techniques for
building  classes and populating them.

* Creating classes on the fly

See [[http://stackoverflow.com/questions/2461751/python-class-factory-using-user-input-as-class-names][this discussion]] on Stack Overflow about how to create
classes on the fly:

#+name: def_meta
#+BEGIN_SRC python :tangle class_templates.py
def meta(_name):
    class cls():
        @staticmethod
        def inv(args):
            pass

    cls.__name__ = _name
    return cls
#+END_SRC

* Class template
** Specification
This is a template for making classes.  The class template
is useful for creating data classes, i.e., classes whose
objects have state variables that are typed and that have an
invariant holding them together.  These data classes come
with a standard set of setters and getters.  Equality
predicate may be added later (see =Temp= example below)


Class templates take a 
 - the name of the class to be created (string)

 - A specification of the names of the state variables and
   their types (dictionary)

 - An invariant which is a function of an instance of the
   class and a dictionary of the state variables.  The
   invariant is optional, but if present is part of the same
   dictionary that specifies the state variables, against
   the key =inv=. 

#+BEGIN_EXAMPLE
   Temp = ClassTemplate.mk_class("Temp", min=is_int, max=is_int, 
                                 inv=lambda self, args: 
								      args["min"] <= args["max"])

   Temp = ClassTemplate.mk_class("Temp", min=is_int, max=is_int, 
                                 inv=lambda self, args: 
								      args["min"] <= args["max"])

#+END_EXAMPLE

=Temp= is now a class with two state variables =min= and
=max=, both satisfying the type predicate =is_int= and
together satisfying the invariant =min= is less than equal
to =max=.  Since =inv= ends up being a method in =Temp=, its
needs to carry as its first argument an object =self=, even
though the invariant itself is defined on elements of the
dictionary =args=.

** Implementation

A class is created with no fields.  It is then mk_classd
with =ClassTemplate.mk_class=, which takes a class and a
dictionary mapping state variable names to their type
checks.  The keywords may contain a field called =inv= which
is mapped to an invariant predicate that returns true or false.

#+BEGIN_SRC python :tangle class_templates.py
from runtime.utils.type_utils.type_utils import *
class ClassTemplate():

#+END_SRC

*** =inv_true=

This invariant predicate always returns true and is used as
the default if no invariant is specified when making a
class.

#+BEGIN_SRC python :tangle class_templates.py
    @staticmethod
    def inv_true(obj, args):
        return True

#+END_SRC

#+BEGIN_SRC python :tangle class_templates.py
    @staticmethod
    def mk_init(cls):
        # obj is an instance of cls
        # args is a dictionary
        def fn(obj, **args): 
            check_dict(args)

#            print "initializer:  cls.sorted_state_vars = %s" % cls.sorted_state_vars
#            print "initializer:  args.keys() = %s" % args.keys()

            # match arg keys with state_vars list
            check_pred(lambda a: sorted(a.keys()) == \
                           sorted(cls.sorted_state_vars))(args)

            obj.state = {}
            
            # each arg should satisfy its typecheck 
            for key, value in args.iteritems():
                cls.state_var_type_checks[key](value)

            # invariant must be true on args
            # check_inv(cls.inv,cls)args)
            if not obj.inv(args):
                raise TypeError("invariant for class %s violated for init args %s" %(cls.__name__, args))

            # initialize the state
            for key, value in args.iteritems():
                obj.state[key] = value


            if cls.is_persistent:
                setattr(obj, 'hide_id', {})

        return fn

#+END_SRC

#+BEGIN_SRC python :tangle class_templates.py
    @staticmethod
    def mk_setter(cls):
        def fn(obj, **args):
            #obj is the object whose variables are being set
            # args is a dictionary of new variable bindings

            check_dict(args)
            if not hasattr(obj, 'state'):
                obj.state = {}
            tmp = obj.state.copy()
            
            for key, value in args.iteritems():
                # arg variables should be a subset of those in the formal spec
                if key in cls.sorted_state_vars:
                    # and they should pass the type checking
                    cls.state_var_type_checks[key](value)
                    # if so update tmp with the new bindings in args
                    tmp[key] = value
                else:
                    raise TypeError("set: Invalid field name %s" % key)  

            # now check the invariant on tmp
            if not obj.inv(tmp):
                raise TypeError("set: arguments %s violate invariant for %s" % (cls.__name__, args))

            # now save the state
            obj.state = tmp

            if 'save_handler' in (cls.custom_handlers):
                cls.custom_handlers['save_handler'](obj, **args)

        return fn

#+END_SRC

*** =mk_eq= method

#+BEGIN_SRC python :tangle class_templates.py
    @staticmethod
    def mk_eq(cls, pred):
        def fn(obj, other):
            return isinstance(other, obj.__class__) and pred(obj, other)
        return fn

#+END_SRC
*** =mk_to_client=

#+BEGIN_SRC python :tangle class_templates.py
    @staticmethod
    def mk_to_client(cls):
        def fn(obj, level=1):
            to_client_var = {}
            for key in cls.sorted_state_vars:
                value = obj.get(key)

                if is_instrumented_list(value) or is_list(value):    
                    to_client_var[key] = []

                    for item in value:
                        if level <= 2:
                            if hasattr(item, 'to_client'):
                                to_client_var[key].append(\
                                    item.to_client(level=level+1))
                            else:
                                to_client_var[key].append(value)
                        else:
                            to_client_var[key].append("Not Printing")
                        
                elif hasattr(value, 'to_client'):
                    to_client_var[key] = value.to_client(level=level+1)
                else:
                    to_client_var[key] = value

            if hasattr(obj, "id"):
                to_client_var["id"] = str(obj.id)

            if hasattr(obj, "hide_id") and 'id' in getattr(obj, "hide_id").keys():
                to_client_var["id"] = str(getattr(obj, "hide_id")["id"])

            return to_client_var

        return fn

#+END_SRC

*** =mk_add_attributes=

#+BEGIN_SRC python :tangle class_templates.py
    @staticmethod
    def mk_add_attributes(cls):
        def fn(**formals):
            
            check_dict(formals)

#            print "formals before if  = %s" % formals
            if 'inv' in formals:
                cls.inv = formals['inv']
                del formals['inv']
#                print "formals after deleting inv  = %s" % formals
            else:
                cls.inv = ClassTemplate.inv_true

            # append the keys of the formals
            cls.sorted_state_vars += formals.keys()

            # create a dictionary of type preds  for the  state variables
            # {'min': is_int, 'max': is_int}
            cls.state_var_type_preds.update(formals.copy())

            # {'min': check_int, 'max': check_int}
            cls.state_var_type_checks = \
            {k: check_pred(v) for k, v in cls.state_var_type_preds.items()}

        return staticmethod(fn)

#+END_SRC

*** =mk_getter= function
    Provides the mechanism to access the attributes of an object.  For a
    persistent object, all the attributes when retrieved from sql database
    using orm, the attributes are saved to a different location.  

#+BEGIN_SRC python :tangle class_templates.py
    @staticmethod
    def mk_getter(cls):
        def fn(obj,k):
            if str(k) and (k in cls.sorted_state_vars):
                if hasattr(obj, 'id') and getattr(obj, 'id') is not None:
                    return getattr(obj, k)
                else:
                    return obj.state[k]
            else:
                raise TypeError("get: Invalid key %s" % k)
        return fn

#+END_SRC

*** =mk_class= method

#+BEGIN_SRC python :tangle class_templates.py
    @staticmethod
    def mk_class(_name, **formals):
#        print "formals for mk_class = %s" % formals
        # name is the name of the class to be created
        # formals is a dictionary of name, type_pred pairs
        # example of formals: 
        # {'min': is_int, 
        #  'max': is_int, 
        #  'inv': lambda self, args: args['min'] <= args['max']}
        
        # check if formals is a dictionary
        if formals:
            check_dict(formals)

        # create a class with name
        cls = meta(_name)

        # set the invariant
        # if absent in formals, use default (inv_true)
#        print "formals before if  = %s" % formals
        if 'inv' in formals:
            cls.inv = formals['inv']
            del formals['inv']
 #           print "formals after deleting inv  = %s" % formals
        else:
            cls.inv = ClassTemplate.inv_true

        # create sorted list of state variables
        # ['max', 'min']
        cls.sorted_state_vars = []
        cls.sorted_state_vars = sorted(formals.keys())

        # create a dictionary of type preds  for the  state variables
        # {'min': is_int, 'max': is_int}
        cls.state_var_type_preds = {}
        cls.state_var_type_checks = {}
        cls.state_var_type_preds=formals.copy()

        # {'min': check_int, 'max': check_int}
        cls.state_var_type_checks = \
        {k: check_pred(v) for k, v in cls.state_var_type_preds.items()}

        cls.add_attributes = ClassTemplate.mk_add_attributes(cls)
        # __init__
        cls.__init__ = ClassTemplate.mk_init(cls)

        # eq
        # to be done
#       cls.__eq__ = ClassTemplate.mk_eq(cls)

        # get
        cls.get = ClassTemplate.mk_getter(cls)

        # set
        cls.set = ClassTemplate.mk_setter(cls)

        # to_client
        cls.to_client = ClassTemplate.mk_to_client(cls)

        cls.custom_handlers = {}
        cls.is_persistent = False
        cls.custom_handlers['persistence'] = False
        return cls

#+END_SRC


* Package 														:boilerplate:
#+BEGIN_SRC python :eval no :tangle __init__.py
print "runtime.utils.class_templates package"
#+END_SRC
